package kdev.example.plugin;

import kd.bos.form.plugin.AbstractFormPlugIn;
import kd.bos.entity.datamodel.IDataModel;
import kd.bos.entity.datamodel.DynamicObject;
import kd.bos.logging.Logger;
import kd.bos.logging.LogFactory;
import kd.bos.form.field.events.PropertyChangedArgs;

/**
 * 表单插件模板
 *
 * 功能:
 * - 字段值变化监听
 * - 保存前验证
 * - 数据处理
 *
 * @author Auto-generated by kingdee-dev-plugin
 * @date 2026-04-30
 */
public class FormPluginTemplate extends AbstractFormPlugIn {

    private static final Logger logger = LogFactory.getLogger(FormPluginTemplate.class);

    // ==================== 字段常量 ====================
    private static final String FIELD_NAME = "name";
    private static final String FIELD_AMOUNT = "amount";

    // ==================== 状态常量 ====================
    private static final int STATUS_DRAFT = 1;
    private static final int STATUS_APPROVED = 2;

    @Override
    public void propertyChanged(PropertyChangedArgs e) {
        super.propertyChanged(e);

        try {
            String fieldName = e.getProperty().getName();

            // 字段变化处理逻辑
            if (FIELD_NAME.equals(fieldName)) {
                handleNameChange();
            }

        } catch (Exception ex) {
            logger.error("字段变化处理失败", ex);
            this.getView().showMessage("操作失败：" + ex.getMessage());
        }
    }

    /**
     * 处理名称字段变化
     */
    private void handleNameChange() {
        IDataModel model = this.getView().getModel();
        String name = (String) model.getValue(FIELD_NAME);

        // 业务逻辑
        logger.info("名称字段变化: {}", name);
    }

    @Override
    public void beforeSave() {
        super.beforeSave();

        try {
            validateBeforeSave();
            logger.info("保存前验证通过");
        } catch (Exception ex) {
            logger.error("保存前验证失败", ex);
            this.getView().showMessage("验证失败：" + ex.getMessage());
            this.getView().getModel().setValue("cancel_save", true);
        }
    }

    /**
     * 保存前验证
     */
    private void validateBeforeSave() {
        IDataModel model = this.getView().getModel();

        // 验证必填字段
        String name = (String) model.getValue(FIELD_NAME);
        if (name == null || name.trim().isEmpty()) {
            throw new RuntimeException("名称不能为空");
        }
    }
}
